config/routes.rb
Henakut::Application.routes.draw do
  resources :commissions

  resources :articles

  resources :categories, :except => [:index, :show]
  resources :forums, :except => :index do
    resources :topics, :shallow => true, :except => :index do
      resources :posts, :shallow => true, :except => [:index, :show]
    end
    root :to => 'categories#index', :via => :get
  end
match'/search' => 'pieces#search'
  resources :profiles

  get "orderitems/index"

  get "orderitems/show"

  get "orderitems/new"

  get "orderitems/edit"

  resources :orders

  devise_for :users

  get "cart/index"

  get "site/about"

  get "site/faq"

  get "site/corporateclient"

  get "site/commissionartwork"

  get "site/commissionartworkindex"

  get "site/becomeanartist"

  resources :artists

  resources :pieces

  get "site/index"

  	resources :orders do
  	resources :orderitems
  	end

	devise_for :users do
	resources :orders
	end

	resources :orders do
	resources :orderitems
	end
	

	match '/checkout' => 'cart#createOrder'
  match '/myprofile' => 'profiles#myprofile' 
	match '/index' => 'site#index'
	match '/about' => 'site#about'
	match '/faq' => 'site#faq'
	match '/corporateclient' => 'site#corporateclient'
  match '/commissionartwork' => 'site#commissionartwork'
  match '/commissionartworkindex' => 'site#commissionartworkindex'
  match '/becomeanartist' => 'site#becomeanartist'

	match '/artstyle/:id' => 'pieces#artstyle'
	match '/artmedium/:id' => 'pieces#artmedium'
	match '/artcolour/:id' => 'pieces#artcolour'
	
	
	match '/cart' => 'cart#index'
	match '/cart/:id' => 'cart#add'
	match '/cart/remove/:id' => 'cart#remove'
	match '/clearCart' => 'cart#clearCart'
	match '/checkout' => 'cart#createOrder'

	
	root :to => 'site#index'
	

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :title
  

has_many :taggings, :dependent => :destroy
has_many :tags, :through => :taggings
validates_presence_of :title, :body
validates_uniqueness_of :title
  attr_writer :tag_names
  after_save :assign_tags
  
  def tag_names
    @tag_names || tags.map(&:name).join(' ')
  end
  
  private
  
  def assign_tags
    if @tag_names
      self.tags = @tag_names.split(/\,/).map do |name|
        Tag.find_or_create_by_name(name)
      end
    end
  end
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :artistimage_url, :artistname, :artstyle, :arttype, :bio, :featuredartist
  has_many :pieces
end

app/models/category.rb
class Category < ActiveRecord::Base
  
  # Associations
  has_many :forums, :dependent => :destroy
  
  # Accessors
  attr_accessible :title, :state, :position, :category_id
  
  # Scopes
  default_scope :order => 'position ASC'
  
  # Validations
  validates :title,       :presence => true
end

app/models/commission.rb
class Commission < ActiveRecord::Base
  attr_accessible :artist, :colour, :email, :name, :style, :image, :remote_image_url

  mount_uploader :image, ImageUploader
end

app/models/forum.rb
class Forum < ActiveRecord::Base
  
  # Associations
  has_many :topics, :dependent => :destroy
  has_many :posts, :through => :topics
  
  belongs_to :category
  
  # Accessors
  attr_accessible :title, :description, :state, :position, :category_id
  
  # Scopes
  default_scope :order => 'position ASC'
  
  # Validations
  validates :title,       :presence => true
  validates :description, :presence => true
  validates :category_id, :presence => true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  attr_accessible :order_date
	
  has_many :orderitems
  belongs_to :user

end

app/models/orderitem.rb
class Orderitem < ActiveRecord::Base
  belongs_to :order
  attr_accessible :description, :item_id, :price, :quantity, :title
end

app/models/piece.rb
class Piece < ActiveRecord::Base
  attr_accessible :artcolour, :artcolour, :artimage_url, :artist_id, :artmedium, :artstyle, :arttype, :name, :price, :stocknumber
  belongs_to :artist


end

app/models/post.rb
class Post < ActiveRecord::Base
  
  # Associations
  belongs_to :forum, :counter_cache => true
  belongs_to :topic, :counter_cache => true, :touch => true 
  belongs_to :user, :class_name => "User", :counter_cache => true
  
  # Accessors
  attr_accessible :body
  
  # Validations
  validates :body, :presence => true
  validates :user, :presence => true
  
  # Default Scope
  default_scope :order => 'created_at ASC'
  
  # Scope to display only the last n posts. Used for "Recent Posts" display
  scope :recent, lambda {
    |c| reorder('created_at desc').limit(c)
  }
  
  # Callbacks
  before_save :topic_locked?
  
  # Methods
  private
    def topic_locked?
      if topic.locked?
        errors.add(:base, "That topic is locked")
        false
      end
    end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  attr_accessible :address, :firstname, :lastname, :mobile, :user_id
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  
  # Associations
  has_many :posts, :dependent => :destroy
  belongs_to :forum, :counter_cache => true
  belongs_to :user, :class_name => "User", :counter_cache => true
  
  # Accessors
  attr_accessor :body
  attr_accessible :title, :body, :sticky, :locked
  
  # Validations
  validates :title,   :presence => true
  validates :body,    :presence => true, :on => :create
  validates :posts,   :presence => true, :allow_nil => false, :on => :update
  validates :user,    :presence => true
  
  # Scopes
  default_scope :order => 'sticky DESC, updated_at DESC'
  
  # Callbacks
  after_create :create_initial_post
  
  # Methods
  def hit!
    self.class.increment_counter :hits, id
  end
  
  private
    def create_initial_post
      self.posts.build(:body => self.body).tap do |post|
        post.forum = self.forum
        post.user = self.user
        post.save
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :orders

  has_one :profiles

  has_many :topics, :dependent => :destroy
  has_many :posts, :dependent => :destroy

end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController 
  def show
    @forum = Forum.find(params[:id])
  end
  
  def new
    @forum = Forum.new
  end
  
  def create
    @forum = Forum.new(params[:forum])
    
    if @forum.save
      flash[:notice] = "Forum was successfully created."
      redirect_to forums_url
    else
      render :action => 'new'
    end
  end
  
  def edit
    @forum = Forum.find(params[:id])
  end
  
  def update
    @forum = Forum.find(params[:id])
    
    if @forum.update_attributes(params[:forum])
      flash[:notice] = "Forum was updated successfully."
      redirect_to forum_url(@forum)
    end
  end
  
  def destroy
    @forum = Forum.find(params[:id])
    
    if @forum.destroy
      flash[:notice] = "Category was deleted."
      redirect_to forums_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	 def sortable(column, title = nil)  
      title ||= column.titleize  
      direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"  
      link_to title, {:sort => column, :direction => direction}
	 end  
	  

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/forums/_form.html.erb
<div class="module">
  <div class="module_header"><%= action_name.humanize %> Forum</div>
    <div class="module_subheader smaller">
      <em>To create a category, leave the category field unselected.</em>
    </div>
    <div class="module_body">
      <%= form_for @forum do |f| %>
      <% if @forum.errors.any? %>
        <% flash.now[:error] = @forum.errors.full_messages.join(', and ') %>
      <% end %>
      <div class="fieldset">
        <span class="label indent smaller">
          <%= f.label :category_id %><br />
          <small>(Required)</small>
        </span>
        <span class="input indent smaller">
          <%= f.collection_select :category_id, Category.all, :id, :title %>
        </span>
        <div class="clear"></div>
      </div>
      <div class="fieldset">
        <span class="label indent smaller">
          <%= f.label :title %><br />
          <small>(Required)</small>
        </span>
        <span class="input indent smaller"><%= f.text_field :title, :size => 75 %></span>
        <div class="clear"></div>
      </div>
      <div class="fieldset">
        <span class="label indent smaller">
          <%= f.label :description %><br />
          <small>(Required)</small>
        </span>
        <span class="input indent smaller"><%= f.text_area :description, :cols => 60, :rows => 5 %></span>
        <div class="clear"></div>
      </div>
      <div class="fieldset">
        <span class="label indent smaller">
          <%= f.label :position %>
        </span>
        <span class="input indent smaller"><%= f.text_field :position %></span>
        <div class="clear"></div>
      </div>
      <div class="fieldset">
        <span class="label indent smaller"></span>
        <span class="input indent smaller">
          <%= f.check_box :state %>
          <%= f.label :state %>
        </span>
        <div class="clear"></div>
      </div>
    </div>
    <div class="module_footer">
      <div class="fieldset">
        <span class="input"><%= f.submit "submit" %> or <%= link_to "cancel", @forum.nil? ? forum_path(@forum) : forums_path %></span>
        <div class="clear"></div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/forums/edit.html.erb
<%= render :partial => 'form' %>

app/views/forums/index.html.erb
  <% if current_user.try(:admin?) %>
  <div class="right controls"><%= link_to "New Forum/Category", new_forum_path %></div>
  <% end %>
<% @categories.each do |category| %>
  <div class="module">
    <div class="module_header">

      <%= category.title %>
      <span class="controls right smaller"> 
      <% if current_user.try(:admin?) %> 
        <%= link_to "New Forum", new_forum_path %>
        <%= link_to "Edit Category", edit_forum_path(category) %>
        <%= link_to "Delete Category", forum_path(category), :confirm => "Are you sure you want to delete this category?", :method => :delete %>
        <% end %> 
      </span>
      
    </div>
    <% if category.forums.size > 0 %>
    <div>
      <table>
        <tr class="smaller">
          <th colspan="2" align="left">Forum</th>
          <th>Topics</th>
          <th>Posts</th>
          <th class="last_post" align="left">Last Post</th>
        </tr>
        <% category.forums.each do |forum| %>
        <tr>
          <td class="icon"><%= image_tag '/assets/icon.png' %></td>
          <td class="description">
            <%= link_to forum.title, forum_path(forum) %><br />
            <span class="smaller"><%= forum.description %></span><br />
          </td>
          <td class="counts smaller"><%= forum.topics.size %></td>
          <td class="counts smaller"><%= forum.posts.size - forum.topics.size %></td>
          <td class="last_post smaller">
            <% if forum.posts.size > 0 %>
              <%= forum.posts.last.created_at %><br />
              <%= forum.posts.last.user.email %>
            <% else %>
              No Topics / Posts
            <% end %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
    <% else %>
      <div class="module_body">There are currently no forums.</div>
    <% end %>
  </div>
<% end %>

app/views/forums/new.html.erb
<%= render :partial => 'form' %>

app/views/forums/show.html.erb
  <% if current_user.try(:admin?) %>
  <div class="right controls"><%= link_to "Back to Forum List", forums_path %></div>
<% end %>
<div class="module">
  <div class="module_header">
    <%= @forum.title %>
    
    <span class="controls right">

      <%= link_to "New Piece", new_forum_topic_path(@forum) %>
      <% if current_user.try(:admin?) %>
      <%= link_to "Edit forum", edit_forum_path(@forum) %>
      <%= link_to "Delete Forum", forum_path(@forum), :confirm => "Are you sure you want to delete this forum?", :method => :delete %>
      <% end %>
    </span>

  </div>
  <div>
    <table>
      <tr class="smaller">
        <th colspan="2" align="left">Topic</th>
        <th>Replies</th>
        <th>Views</th>
        <th class="last_post" align="left">Last Post</th>
      </tr>
      <% @forum.topics.each do |topic| %>
      <tr>
        <td class="icon"><%= image_tag '/assets/icon.png' %></td>
        <td class="description">
          <%= link_to topic.title, topic_path(topic) %><br />
          <span class="smaller">by <%= topic.user.email %></span>
        </td>
        <td class="counts smaller"><%= topic.posts.size - 1 %></td>
        <td class="counts smaller"><%= topic.hits %></td>
        <td class="last_post smaller">
          <%= topic.posts.last.created_at %><br />
          by <%= topic.posts.last.user.email %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>