config/routes.rb
Henakut::Application.routes.draw do
  resources :commissions

  resources :articles

  resources :categories, :except => [:index, :show]
  resources :forums, :except => :index do
    resources :topics, :shallow => true, :except => :index do
      resources :posts, :shallow => true, :except => [:index, :show]
    end
    root :to => 'categories#index', :via => :get
  end
match'/search' => 'pieces#search'
  resources :profiles

  get "orderitems/index"

  get "orderitems/show"

  get "orderitems/new"

  get "orderitems/edit"

  resources :orders

  devise_for :users

  get "cart/index"

  get "site/about"

  get "site/faq"

  get "site/corporateclient"

  get "site/commissionartwork"

  get "site/commissionartworkindex"

  get "site/becomeanartist"

  resources :artists

  resources :pieces

  get "site/index"

  	resources :orders do
  	resources :orderitems
  	end

	devise_for :users do
	resources :orders
	end

	resources :orders do
	resources :orderitems
	end
	

	match '/checkout' => 'cart#createOrder'
  match '/myprofile' => 'profiles#myprofile' 
	match '/index' => 'site#index'
	match '/about' => 'site#about'
	match '/faq' => 'site#faq'
	match '/corporateclient' => 'site#corporateclient'
  match '/commissionartwork' => 'site#commissionartwork'
  match '/commissionartworkindex' => 'site#commissionartworkindex'
  match '/becomeanartist' => 'site#becomeanartist'

	match '/artstyle/:id' => 'pieces#artstyle'
	match '/artmedium/:id' => 'pieces#artmedium'
	match '/artcolour/:id' => 'pieces#artcolour'
	
	
	match '/cart' => 'cart#index'
	match '/cart/:id' => 'cart#add'
	match '/cart/remove/:id' => 'cart#remove'
	match '/clearCart' => 'cart#clearCart'
	match '/checkout' => 'cart#createOrder'

	
	root :to => 'site#index'
	

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :artistimage_url, :artistname, :artstyle, :arttype, :bio, :featuredartist
  has_many :pieces
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  # GET /artists
  # GET /artists.json
before_filter :ensure_admin, :except => [:index, :show, :category, :search]

def ensure_admin
    unless current_user && current_user.admin?
      render :text => "You dont have the access to do this!", :status => :unauthorized
    end
end



  def index
    @artists = Artist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @artists }
    end
  end
  
  # GET /artists/1
  # GET /artists/1.json
  def show
    @artist = Artist.find(params[:id])
	
	@pieces = @artist.pieces
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/new
  # GET /artists/new.json
  def new
    @artist = Artist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/1/edit
  def edit
    @artist = Artist.find(params[:id])
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(params[:artist])

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render json: @artist, status: :created, location: @artist }
      else
        format.html { render action: "new" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /artists/1
  # PUT /artists/1.json
  def update
    @artist = Artist.find(params[:id])

    respond_to do |format|
      if @artist.update_attributes(params[:artist])
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to artists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_featuredartist.html.erb
<% @feartists = Artist.where(:featuredartist => true).limit(4) %>

<% @feartists.each do |artist| %>



<div class="photos">
<%= link_to (image_tag artist.artistimage_url, :style => "height:100px"), artist %>
<br />
<%= link_to artist.artistname, artist %> 
</div>
<% end %>
<br />

app/views/artists/_featuredartists.html.erb
<%= @featured.each do |featured| %>
<div class="photos">
<%= link_to (image_tag artist.artistimage_url, :style => "height:100px"), artist %>
<br />
<%= link_to artist.artistname, artist %>
</div>

<% end %>

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :artistname %><br />
    <%= f.text_field :artistname %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :artistimage_url %><br />
    <%= f.text_field :artistimage_url %>
  </div>
  <div class="field">
    <%= f.label :arttype %><br />
    <%= f.text_field :arttype %>
  </div>
  <div class="field">
    <%= f.label :artstyle %><br />
    <%= f.text_field :artstyle %>
  </div>
  <div class="field">
    <%= f.label :featuredartist %><br />
    <%= f.check_box :featuredartist %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<div class="lefthone">
<h2>Browse Artists</h2><img src="/assets/linebreak.jpg" />
</div>

<% @artists.each do |artist| %>



<div class="photos">
<%= link_to (image_tag artist.artistimage_url), artist %>
<br />
<%= link_to artist.artistname, artist %> 
<br />

<% if current_user.try(:admin?) %>
<%= link_to 'Edit', edit_artist_path(artist) %> |
<%= link_to 'Destroy', artist, :confirm => 'Are you sure?', :method => :delete %>
<%= link_to 'New Artist', new_artist_path %>
<% end %>

</div>
<% end %>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>
<script type="text/javascript">
$(document).ready(function(){
$("table img").hover(function(){
$("#main").attr("src",($(this).attr("src")));
});
});

</script>
<div class="sidepaintings">

<table>
<tr>
<% @pieces.each_with_index do |piece,index| %>
	<% if (index %4) == 0 %>
		</tr><tr>
	<%end%>	
	<td>
		<%= link_to image_tag(piece.artimage_url, :mouseover => "MM_swapImage('main','','#{piece.artimage_url}',1)"), piece_path(piece.id) %>
	</td>

<% end %>
</tr>
</table>



    <p>&nbsp;</p>
   
    <p>&nbsp;</p>
  </div>
    <div class="selectedpainting">
    <p>&nbsp;</p>
    <%= image_tag(@pieces.first.artimage_url, :name=> "main", :id=>"main") %>
    <p>&nbsp;</p>
    </div>
<div class="artistdetails">
    <div class="lefthone">
<h2><%= @artist.artistname %></h2><img src="/assets/linebreak.jpg" />

</div>
    
      
      <p><%= @artist.bio %></p>
    </div>

<% if current_user.try(:admin?) %>
<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>
<% end %>