config/routes.rb
Henakut::Application.routes.draw do
  resources :commissions

  resources :articles

  resources :categories, :except => [:index, :show]
  resources :forums, :except => :index do
    resources :topics, :shallow => true, :except => :index do
      resources :posts, :shallow => true, :except => [:index, :show]
    end
    root :to => 'categories#index', :via => :get
  end
match'/search' => 'pieces#search'
  resources :profiles

  get "orderitems/index"

  get "orderitems/show"

  get "orderitems/new"

  get "orderitems/edit"

  resources :orders

  devise_for :users

  get "cart/index"

  get "site/about"

  get "site/faq"

  get "site/corporateclient"

  get "site/commissionartwork"

  get "site/commissionartworkindex"

  get "site/becomeanartist"

  resources :artists

  resources :pieces

  get "site/index"

  	resources :orders do
  	resources :orderitems
  	end

	devise_for :users do
	resources :orders
	end

	resources :orders do
	resources :orderitems
	end
	

	match '/checkout' => 'cart#createOrder'
  match '/myprofile' => 'profiles#myprofile' 
	match '/index' => 'site#index'
	match '/about' => 'site#about'
	match '/faq' => 'site#faq'
	match '/corporateclient' => 'site#corporateclient'
  match '/commissionartwork' => 'site#commissionartwork'
  match '/commissionartworkindex' => 'site#commissionartworkindex'
  match '/becomeanartist' => 'site#becomeanartist'

	match '/artstyle/:id' => 'pieces#artstyle'
	match '/artmedium/:id' => 'pieces#artmedium'
	match '/artcolour/:id' => 'pieces#artcolour'
	
	
	match '/cart' => 'cart#index'
	match '/cart/:id' => 'cart#add'
	match '/cart/remove/:id' => 'cart#remove'
	match '/clearCart' => 'cart#clearCart'
	match '/checkout' => 'cart#createOrder'

	
	root :to => 'site#index'
	

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :title
  

has_many :taggings, :dependent => :destroy
has_many :tags, :through => :taggings
validates_presence_of :title, :body
validates_uniqueness_of :title
  attr_writer :tag_names
  after_save :assign_tags
  
  def tag_names
    @tag_names || tags.map(&:name).join(' ')
  end
  
  private
  
  def assign_tags
    if @tag_names
      self.tags = @tag_names.split(/\,/).map do |name|
        Tag.find_or_create_by_name(name)
      end
    end
  end
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :artistimage_url, :artistname, :artstyle, :arttype, :bio, :featuredartist
  has_many :pieces
end

app/models/category.rb
class Category < ActiveRecord::Base
  
  # Associations
  has_many :forums, :dependent => :destroy
  
  # Accessors
  attr_accessible :title, :state, :position, :category_id
  
  # Scopes
  default_scope :order => 'position ASC'
  
  # Validations
  validates :title,       :presence => true
end

app/models/commission.rb
class Commission < ActiveRecord::Base
  attr_accessible :artist, :colour, :email, :name, :style, :image, :remote_image_url

  mount_uploader :image, ImageUploader
end

app/models/forum.rb
class Forum < ActiveRecord::Base
  
  # Associations
  has_many :topics, :dependent => :destroy
  has_many :posts, :through => :topics
  
  belongs_to :category
  
  # Accessors
  attr_accessible :title, :description, :state, :position, :category_id
  
  # Scopes
  default_scope :order => 'position ASC'
  
  # Validations
  validates :title,       :presence => true
  validates :description, :presence => true
  validates :category_id, :presence => true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  attr_accessible :order_date
	
  has_many :orderitems
  belongs_to :user

end

app/models/orderitem.rb
class Orderitem < ActiveRecord::Base
  belongs_to :order
  attr_accessible :description, :item_id, :price, :quantity, :title
end

app/models/piece.rb
class Piece < ActiveRecord::Base
  attr_accessible :artcolour, :artcolour, :artimage_url, :artist_id, :artmedium, :artstyle, :arttype, :name, :price, :stocknumber
  belongs_to :artist


end

app/models/post.rb
class Post < ActiveRecord::Base
  
  # Associations
  belongs_to :forum, :counter_cache => true
  belongs_to :topic, :counter_cache => true, :touch => true 
  belongs_to :user, :class_name => "User", :counter_cache => true
  
  # Accessors
  attr_accessible :body
  
  # Validations
  validates :body, :presence => true
  validates :user, :presence => true
  
  # Default Scope
  default_scope :order => 'created_at ASC'
  
  # Scope to display only the last n posts. Used for "Recent Posts" display
  scope :recent, lambda {
    |c| reorder('created_at desc').limit(c)
  }
  
  # Callbacks
  before_save :topic_locked?
  
  # Methods
  private
    def topic_locked?
      if topic.locked?
        errors.add(:base, "That topic is locked")
        false
      end
    end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  attr_accessible :address, :firstname, :lastname, :mobile, :user_id
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  
  # Associations
  has_many :posts, :dependent => :destroy
  belongs_to :forum, :counter_cache => true
  belongs_to :user, :class_name => "User", :counter_cache => true
  
  # Accessors
  attr_accessor :body
  attr_accessible :title, :body, :sticky, :locked
  
  # Validations
  validates :title,   :presence => true
  validates :body,    :presence => true, :on => :create
  validates :posts,   :presence => true, :allow_nil => false, :on => :update
  validates :user,    :presence => true
  
  # Scopes
  default_scope :order => 'sticky DESC, updated_at DESC'
  
  # Callbacks
  after_create :create_initial_post
  
  # Methods
  def hit!
    self.class.increment_counter :hits, id
  end
  
  private
    def create_initial_post
      self.posts.build(:body => self.body).tap do |post|
        post.forum = self.forum
        post.user = self.user
        post.save
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :orders

  has_one :profiles

  has_many :topics, :dependent => :destroy
  has_many :posts, :dependent => :destroy

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController  
  def show
    @topic = Topic.find(params[:id])
    @topic.hit! if @topic
  end
  
  def new
    @forum = Forum.find(params[:forum_id])
    @topic = Topic.new
  end
  
  def create
    @forum = Forum.find(params[:forum_id])
    @topic = @forum.topics.build(params[:topic])
    @topic.user = current_user
    
    if @topic.save
      flash[:notice] = "Topic was successfully created."
      redirect_to topic_url(@topic)
    else
      render :action => 'new'
    end
  end
  
  def edit
    @topic = Topic.find(params[:id])
  end
  
  def update
    @topic = Topic.find(params[:id])
    
    if @topic.update_attributes(params[:topic])
      flash[:notice] = "Topic was updated successfully."
      redirect_to topic_url(@topic)
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    
    if @topic.destroy
      flash[:notice] = "Topic was deleted successfully."
      redirect_to forum_url(@topic.forum)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	 def sortable(column, title = nil)  
      title ||= column.titleize  
      direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"  
      link_to title, {:sort => column, :direction => direction}
	 end  
	  

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/topics/_form.html.erb
<%= form_for [@forum, @topic] do |f| %>
<% if @topic.errors.any? %>
  <% flash.now[:error] = @topic.errors.full_messages.join(', and ') %>
<% end %>
<div class="module">
  <div class="module_header"><%= action_name.humanize %> Topic</div>
    <div class="module_subheader smaller"></div>
    <div class="module_body">
      <div class="fieldset">
        <span class="label indent smaller">
          <%= f.label :title %><br />
          <small>(Required)</small>
        </span>
        <span class="input indent smaller"><%= f.text_field :title, :size => 75 %></span>
        <div class="clear"></div>
      </div>
      <% unless @topic.id %>
      <div class="fieldset">
        <span class="label indent smaller">
          <%= f.label :body %><br />
          <small>(Required)</small>
        </span>
        <span class="input indent smaller"><%= f.text_area :body, :cols => 60, :rows => 15 %></span>
        <div class="clear"></div>
      </div>
    </div>
    <% end %>
    <div class="module_footer">
      <div class="fieldset">
        <span class="input"><%= f.submit "submit" %> or <%= link_to "cancel", @topic.nil? ?  @topic : @forum %></span>
        <div class="clear"></div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/topics/edit.html.erb
<%= render :partial => 'form' %>

app/views/topics/new.html.erb
<%= render :partial => 'form' %>

app/views/topics/show.html.erb
<div class="right controls"><%= link_to "Back to Forum", forum_path(@topic.forum) %></div>
<div class="module">
  <div class="module_header">
    <%= @topic.title %>
    <span class="right controls">
      <%= link_to "Edit", edit_topic_path(@topic) %>
      <%= link_to "Delete", @topic, :confirm => "Are you sure?", :method => :delete %>
      <%= link_to @topic.sticky ? "Unstick" : "Sticky", {:controller => 'topics', :action => 'update', :topic => {:sticky => @topic.sticky ? "false" : "true" }}, :method => :put %>
      <%= link_to @topic.locked ? "Unlock" : "Lock", {:controller => 'topics', :action => 'update', :topic => {:locked => @topic.locked ? "false" : "true" }}, :method => :put %>
    </span>
  </div>
  <div>
    <table>
      <% @topic.posts.each do |post| %>
      <tr>
        <td class="post_author" rowspan="2">
          <span class="name"><%= post.user.email %></span>
          <span class="avatar"><!-- This space reserved for Avatar --></span>
          <span class="info smaller">
            Posts <%= post.user.posts.size %><br />
            Registered <%= post.user.created_at.to_s(:joined) %><br />
          </span>
        </td>
        <td class="post_header">
          <span class="left post_date smaller">Posted <%= post.created_at %></span>
          <span class="right controls">
            <%= link_to "Reply", new_topic_post_path(@topic) %>
            <%= link_to "Quote", new_topic_post_path(@topic, :quote => post) %>
            <%= link_to "Edit", edit_post_path(post) %>
            <%= link_to "Delete", post, :confirm => "Are you sure?", :method => :delete %>
          </span>
        </td>
      </tr>
      <tr>
        <td class="post_body">
          <%= simple_format(auto_link(post.body)) %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>